// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpaanznummcovcpyxdet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwYWFuem51bW1jb3ZjcHl4ZGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU0Nzg1OTIsImV4cCI6MjA1MTA1NDU5Mn0.I7R6hYsQ0eRzOPnl_X26J4VQ3yxBCyBobnm94njNDxo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);